package com.services.osp.serv;


import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.services.osp.model.ModelResponse;
import com.services.osp.model.OSPModelRequest;

@RestController
@RequestMapping(path = "/OSP")
public class osp {
    
   
    
    @RequestMapping(method = RequestMethod.POST, 
            consumes = "application/json", produces = "application/json", 
            path = "/AllocateResource")
    public @ResponseBody String postUsuario(@RequestBody OSPModelRequest request) {
        ModelResponse respuesta = new ModelResponse();
        
        if(OSPModelRequest.class != null) {
        	ModelResponse.setStatus ("{\r\n"
					+ "    \"allocateResourceResponse\": {\r\n"
					+ "        \"result\": {\r\n"
					+ "            \"code\": 0\r\n"
					+ "        },\r\n"
					+ "        \"rfslastmile\": [{\r\n"
					+ "                \"rfsid\": \"RLM_42000120202203150921455731917008\",\r\n"
					+ "                \"mediaType\": 2,\r\n"
					+ "                \"ospCircuitID\": \"220315092330182666242\",\r\n"
					+ "                \"circuitStatus\": 1,\r\n"
					+ "                \"workgroup\": \"OH_BOLZTCDEB_I_C300\",\r\n"
					+ "                \"cityCode\": 13001000,\r\n"
					+ "                \"centralCode\": \"130010006\",\r\n"
					+ "                \"maxBandwidth\": 0,\r\n"
					+ "                \"extPosition\": {\r\n"
					+ "                    \"distFrameCode\": \"P01GP0101-130011006\",\r\n"
					+ "                    \"rack\": \"01A PI\",\r\n"
					+ "                    \"bloque\": \"03G\",\r\n"
					+ "                    \"regleta\": \"S03\",\r\n"
					+ "                    \"posicion\": 12\r\n"
					+ "                }\r\n"
					+ "            }\r\n"
					+ "        ],\r\n"
					+ "        \"completeInformations\": [{\r\n"
					+ "                \"level\": 1,\r\n"
					+ "                \"circuitType\": \"2\",\r\n"
					+ "                \"massive\": 0,\r\n"
					+ "                \"resourceOrder\": \"RLM_42000120202203150921455731917008\",\r\n"
					+ "                \"circuitQuantity\": 1,\r\n"
					+ "                \"transmissionUnits\": 1,\r\n"
					+ "                \"statusNetwork\": \"0\",\r\n"
					+ "                \"resourceOrderInfoBD\": [],\r\n"
					+ "                \"relatedCircuits\": {\r\n"
					+ "                    \"circuit\": [{\r\n"
					+ "                            \"circuitIdentifier\": \"220315092330182666242\",\r\n"
					+ "                            \"circuitStatus\": 1,\r\n"
					+ "                            \"characteristic\": \"0\",\r\n"
					+ "                            \"resources\": {\r\n"
					+ "                                \"relatedInicialResources\": [{\r\n"
					+ "                                        \"initialResource\": {\r\n"
					+ "                                            \"type\": 14,\r\n"
					+ "                                            \"code\": \"OH_BOLZTCDEB_I_C300\",\r\n"
					+ "                                            \"equipmentStructure\": {\r\n"
					+ "                                                \"rack\": \"2\",\r\n"
					+ "                                                \"subRack\": \"33\",\r\n"
					+ "                                                \"board\": \"GTGH\",\r\n"
					+ "                                                \"slot\": \"4\"\r\n"
					+ "                                            },\r\n"
					+ "                                            \"logicalUnit\": 4,\r\n"
					+ "                                            \"resourceSpecification\": {\r\n"
					+ "                                                \"model\": \"ZXA10 C300-1\",\r\n"
					+ "                                                \"manufacturer\": \"ZTE\"\r\n"
					+ "                                            },\r\n"
					+ "                                            \"resourceCharacterist\": {\r\n"
					+ "                                                \"siteCode\": \"130010006\",\r\n"
					+ "                                                \"cityCode\": 13001000,\r\n"
					+ "                                                \"coordinateX\": -75.4814628464314,\r\n"
					+ "                                                \"coordinateY\": 10.3943924074304,\r\n"
					+ "                                                \"addressGPS\": \"(13001000) CARTAGENA\",\r\n"
					+ "                                                \"subUnit\": []\r\n"
					+ "                                            },\r\n"
					+ "                                            \"terminalLogicalCable\": [],\r\n"
					+ "                                            \"vlan\": []\r\n"
					+ "                                        },\r\n"
					+ "                                        \"initialLogicalCable\": {\r\n"
					+ "                                            \"regionCode\": 13001000,\r\n"
					+ "                                            \"siteCode\": \"130010006\",\r\n"
					+ "                                            \"code\": \"GA-04\",\r\n"
					+ "                                            \"function\": 6,\r\n"
					+ "                                            \"logicalUnit\": 40,\r\n"
					+ "                                            \"availableLogicalUnit\": []\r\n"
					+ "                                        }\r\n"
					+ "                                    }\r\n"
					+ "                                ],\r\n"
					+ "                                \"relatedIntermediaryResources\": [{\r\n"
					+ "                                        \"intermediaryResource\": {\r\n"
					+ "                                            \"type\": 4,\r\n"
					+ "                                            \"code\": \"SP40-04\",\r\n"
					+ "                                            \"buildingFlag\": 0,\r\n"
					+ "                                            \"resourceSpecification\": {\r\n"
					+ "                                                \"code\": \"SPL9102\",\r\n"
					+ "                                                \"model\": \"SPL9102\",\r\n"
					+ "                                                \"manufacturer\": \"HUAWEI\",\r\n"
					+ "                                                \"capacity\": 8\r\n"
					+ "                                            },\r\n"
					+ "                                            \"terminalLogicalCable\": [],\r\n"
					+ "                                            \"vlan\": []\r\n"
					+ "                                        },\r\n"
					+ "                                        \"intermediaryLogicalCable\": {\r\n"
					+ "                                            \"regionCode\": 13001000,\r\n"
					+ "                                            \"siteCode\": \"130010006\",\r\n"
					+ "                                            \"code\": \"GA-04\",\r\n"
					+ "                                            \"function\": 6,\r\n"
					+ "                                            \"logicalUnit\": 40,\r\n"
					+ "                                            \"availableLogicalUnit\": []\r\n"
					+ "                                        }\r\n"
					+ "                                    }, {\r\n"
					+ "                                        \"intermediaryResource\": {\r\n"
					+ "                                            \"type\": 4,\r\n"
					+ "                                            \"code\": \"SS7-40-04\",\r\n"
					+ "                                            \"buildingFlag\": 0,\r\n"
					+ "                                            \"resourceSpecification\": {\r\n"
					+ "                                                \"code\": \"SPL9102\",\r\n"
					+ "                                                \"model\": \"SPL9102\",\r\n"
					+ "                                                \"manufacturer\": \"HUAWEI\",\r\n"
					+ "                                               \"capacity\": 8\r\n"
					+ "                                            },\r\n"
					+ "                                            \"resourceCharacterist\": {\r\n"
					+ "                                                \"siteCode\": \"130010006\",\r\n"
					+ "                                                \"cityCode\": 13001000,\r\n"
					+ "                                                \"coordinateX\": -75.4664155082553,\r\n"
					+ "                                                \"coordinateY\": 10.3977880445217,\r\n"
					+ "                                                \"addressGPS\": \"(13001000) CARTAGENA\",\r\n"
					+ "                                                \"subUnit\": []\r\n"
					+ "                                            },\r\n"
					+ "                                            \"terminalLogicalCable\": [],\r\n"
					+ "                                            \"vlan\": []\r\n"
					+ "                                        },\r\n"
					+ "                                        \"intermediaryLogicalCable\": {\r\n"
					+ "                                            \"regionCode\": 13001000,\r\n"
					+ "                                            \"siteCode\": \"130010006\",\r\n"
					+ "                                            \"code\": \"GD40-04\",\r\n"
					+ "                                            \"function\": 7,\r\n"
					+ "                                            \"logicalUnit\": 7,\r\n"
					+ "                                            \"availableLogicalUnit\": []\r\n"
					+ "                                        }\r\n"
					+ "                                    }\r\n"
					+ "                                ],\r\n"
					+ "                                \"relatedTerminalResources\": [{\r\n"
					+ "                                        \"terminalResource\": {\r\n"
					+ "                                            \"type\": 15,\r\n"
					+ "                                            \"code\": \"PC7-40-04\",\r\n"
					+ "                                            \"terminalSiteCode\": \"CTG-CTO1-36-04 I CTG-CTO7-40-04\",\r\n"
					+ "                                            \"buildingFlag\": 0,\r\n"
					+ "                                            \"resourceSpecification\": {\r\n"
					+ "                                                \"model\": \"FDB2103T-8\",\r\n"
					+ "                                                \"manufacturer\": \"HUAWEI\"\r\n"
					+ "                                            },\r\n"
					+ "                                            \"resourceCharacterist\": {\r\n"
					+ "                                                \"siteCode\": \"130010006\",\r\n"
					+ "                                                \"cityCode\": 13001000,\r\n"
					+ "                                                \"coordinateX\": -76.5147653444791,\r\n"
					+ "                                                \"coordinateY\": 3.37225504891685,\r\n"
					+ "                                                \"addressGPS\": \"(13001000) CARTAGENA\",\r\n"
					+ "                                                \"subUnit\": []\r\n"
					+ "                                            },\r\n"
					+ "                                            \"terminalLogicalCable\": [],\r\n"
					+ "                                            \"vlan\": []\r\n"
					+ "                                        },\r\n"
					+ "                                        \"terminalLogicalCable\": {\r\n"
					+ "                                            \"regionCode\": 13001000,\r\n"
					+ "                                            \"siteCode\": \"130010006\",\r\n"
					+ "                                            \"code\": \"GT7-40-04\",\r\n"
					+ "                                            \"function\": 7,\r\n"
					+ "                                            \"logicalUnit\": 1,\r\n"
					+ "                                            \"availableLogicalUnit\": []\r\n"
					+ "                                        }\r\n"
					+ "                                    }\r\n"
					+ "                                ],\r\n"
					+ "                                \"relatedAditionalResources\": []\r\n"
					+ "                            }\r\n"
					+ "                        }\r\n"
					+ "                    ]\r\n"
					+ "                },\r\n"
					+ "                \"supplementaryInformation\": {\r\n"
					+ "                    \"resourceOrderInfo\": {\r\n"
					+ "                        \"resourceOrderType\": \"OS\",\r\n"
					+ "                        \"resourceOrderDate\": \"2022-03-15T05:00:00.000Z\"\r\n"
					+ "                    },\r\n"
					+ "                    \"subscriberAddress\": {\r\n"
					+ "                        \"streetType\": \"DG\",\r\n"
					+ "                        \"streetName\": \"38\",\r\n"
					+ "                        \"streetCode\": \"SERV15543\",\r\n"
					+ "                        \"streetNumber\": \"TV 54-210\",\r\n"
					+ "                        \"subUnit\": [],\r\n"
					+ "                        \"city\": \"CARTAGENA\",\r\n"
					+ "                        \"stateAcronym\": \"BOL\",\r\n"
					+ "                        \"country\": \"Colombia\",\r\n"
					+ "                        \"regionCode\": 13001000,\r\n"
					+ "                        \"coordinateX\": -75.4660626852322,\r\n"
					+ "                        \"coordinateY\": 10.3967229047298\r\n"
					+ "                    },\r\n"
					+ "                    \"fiberSite\": 1,\r\n"
					+ "                    \"clientLogicalPosition\": 2\r\n"
					+ "                }\r\n"
					+ "            }\r\n"
					+ "        ]\r\n"
					+ "    },\r\n"
					+ "    \"result\": {\r\n"
					+ "        \"resultCode\": 0,\r\n"
					+ "        \"resultDescription\": \"OK\"\r\n"
					+ "    }\r\n"
					+ "}\r\n"
					+ "");
        	
        }
        		
     	
        return "{\r\n"
		+ "    \"allocateResourceResponse\": {\r\n"
		+ "        \"result\": {\r\n"
		+ "            \"code\": 0\r\n"
		+ "        },\r\n"
		+ "        \"rfslastmile\": [{\r\n"
		+ "                \"rfsid\": \"RLM_42000120202203150921455731917008\",\r\n"
		+ "                \"mediaType\": 2,\r\n"
		+ "                \"ospCircuitID\": \"220315092330182666242\",\r\n"
		+ "                \"circuitStatus\": 1,\r\n"
		+ "                \"workgroup\": \"OH_BOLZTCDEB_I_C300\",\r\n"
		+ "                \"cityCode\": 13001000,\r\n"
		+ "                \"centralCode\": \"130010006\",\r\n"
		+ "                \"maxBandwidth\": 0,\r\n"
		+ "                \"extPosition\": {\r\n"
		+ "                    \"distFrameCode\": \"P01GP0101-130011006\",\r\n"
		+ "                    \"rack\": \"01A PI\",\r\n"
		+ "                    \"bloque\": \"03G\",\r\n"
		+ "                    \"regleta\": \"S03\",\r\n"
		+ "                    \"posicion\": 12\r\n"
		+ "                }\r\n"
		+ "            }\r\n"
		+ "        ],\r\n"
		+ "        \"completeInformations\": [{\r\n"
		+ "                \"level\": 1,\r\n"
		+ "                \"circuitType\": \"2\",\r\n"
		+ "                \"massive\": 0,\r\n"
		+ "                \"resourceOrder\": \"RLM_42000120202203150921455731917008\",\r\n"
		+ "                \"circuitQuantity\": 1,\r\n"
		+ "                \"transmissionUnits\": 1,\r\n"
		+ "                \"statusNetwork\": \"0\",\r\n"
		+ "                \"resourceOrderInfoBD\": [],\r\n"
		+ "                \"relatedCircuits\": {\r\n"
		+ "                    \"circuit\": [{\r\n"
		+ "                            \"circuitIdentifier\": \"220315092330182666242\",\r\n"
		+ "                            \"circuitStatus\": 1,\r\n"
		+ "                            \"characteristic\": \"0\",\r\n"
		+ "                            \"resources\": {\r\n"
		+ "                                \"relatedInicialResources\": [{\r\n"
		+ "                                        \"initialResource\": {\r\n"
		+ "                                            \"type\": 14,\r\n"
		+ "                                            \"code\": \"OH_BOLZTCDEB_I_C300\",\r\n"
		+ "                                            \"equipmentStructure\": {\r\n"
		+ "                                                \"rack\": \"2\",\r\n"
		+ "                                                \"subRack\": \"33\",\r\n"
		+ "                                                \"board\": \"GTGH\",\r\n"
		+ "                                                \"slot\": \"4\"\r\n"
		+ "                                            },\r\n"
		+ "                                            \"logicalUnit\": 4,\r\n"
		+ "                                            \"resourceSpecification\": {\r\n"
		+ "                                                \"model\": \"ZXA10 C300-1\",\r\n"
		+ "                                                \"manufacturer\": \"ZTE\"\r\n"
		+ "                                            },\r\n"
		+ "                                            \"resourceCharacterist\": {\r\n"
		+ "                                                \"siteCode\": \"130010006\",\r\n"
		+ "                                                \"cityCode\": 13001000,\r\n"
		+ "                                                \"coordinateX\": -75.4814628464314,\r\n"
		+ "                                                \"coordinateY\": 10.3943924074304,\r\n"
		+ "                                                \"addressGPS\": \"(13001000) CARTAGENA\",\r\n"
		+ "                                                \"subUnit\": []\r\n"
		+ "                                            },\r\n"
		+ "                                            \"terminalLogicalCable\": [],\r\n"
		+ "                                            \"vlan\": []\r\n"
		+ "                                        },\r\n"
		+ "                                        \"initialLogicalCable\": {\r\n"
		+ "                                            \"regionCode\": 13001000,\r\n"
		+ "                                            \"siteCode\": \"130010006\",\r\n"
		+ "                                            \"code\": \"GA-04\",\r\n"
		+ "                                            \"function\": 6,\r\n"
		+ "                                            \"logicalUnit\": 40,\r\n"
		+ "                                            \"availableLogicalUnit\": []\r\n"
		+ "                                        }\r\n"
		+ "                                    }\r\n"
		+ "                                ],\r\n"
		+ "                                \"relatedIntermediaryResources\": [{\r\n"
		+ "                                        \"intermediaryResource\": {\r\n"
		+ "                                            \"type\": 4,\r\n"
		+ "                                            \"code\": \"SP40-04\",\r\n"
		+ "                                            \"buildingFlag\": 0,\r\n"
		+ "                                            \"resourceSpecification\": {\r\n"
		+ "                                                \"code\": \"SPL9102\",\r\n"
		+ "                                                \"model\": \"SPL9102\",\r\n"
		+ "                                                \"manufacturer\": \"HUAWEI\",\r\n"
		+ "                                                \"capacity\": 8\r\n"
		+ "                                            },\r\n"
		+ "                                            \"terminalLogicalCable\": [],\r\n"
		+ "                                            \"vlan\": []\r\n"
		+ "                                        },\r\n"
		+ "                                        \"intermediaryLogicalCable\": {\r\n"
		+ "                                            \"regionCode\": 13001000,\r\n"
		+ "                                            \"siteCode\": \"130010006\",\r\n"
		+ "                                            \"code\": \"GA-04\",\r\n"
		+ "                                            \"function\": 6,\r\n"
		+ "                                            \"logicalUnit\": 40,\r\n"
		+ "                                            \"availableLogicalUnit\": []\r\n"
		+ "                                        }\r\n"
		+ "                                    }, {\r\n"
		+ "                                        \"intermediaryResource\": {\r\n"
		+ "                                            \"type\": 4,\r\n"
		+ "                                            \"code\": \"SS7-40-04\",\r\n"
		+ "                                            \"buildingFlag\": 0,\r\n"
		+ "                                            \"resourceSpecification\": {\r\n"
		+ "                                                \"code\": \"SPL9102\",\r\n"
		+ "                                                \"model\": \"SPL9102\",\r\n"
		+ "                                                \"manufacturer\": \"HUAWEI\",\r\n"
		+ "                                               \"capacity\": 8\r\n"
		+ "                                            },\r\n"
		+ "                                            \"resourceCharacterist\": {\r\n"
		+ "                                                \"siteCode\": \"130010006\",\r\n"
		+ "                                                \"cityCode\": 13001000,\r\n"
		+ "                                                \"coordinateX\": -75.4664155082553,\r\n"
		+ "                                                \"coordinateY\": 10.3977880445217,\r\n"
		+ "                                                \"addressGPS\": \"(13001000) CARTAGENA\",\r\n"
		+ "                                                \"subUnit\": []\r\n"
		+ "                                            },\r\n"
		+ "                                            \"terminalLogicalCable\": [],\r\n"
		+ "                                            \"vlan\": []\r\n"
		+ "                                        },\r\n"
		+ "                                        \"intermediaryLogicalCable\": {\r\n"
		+ "                                            \"regionCode\": 13001000,\r\n"
		+ "                                            \"siteCode\": \"130010006\",\r\n"
		+ "                                            \"code\": \"GD40-04\",\r\n"
		+ "                                            \"function\": 7,\r\n"
		+ "                                            \"logicalUnit\": 7,\r\n"
		+ "                                            \"availableLogicalUnit\": []\r\n"
		+ "                                        }\r\n"
		+ "                                    }\r\n"
		+ "                                ],\r\n"
		+ "                                \"relatedTerminalResources\": [{\r\n"
		+ "                                        \"terminalResource\": {\r\n"
		+ "                                            \"type\": 15,\r\n"
		+ "                                            \"code\": \"PC7-40-04\",\r\n"
		+ "                                            \"terminalSiteCode\": \"CTG-CTO1-36-04 I CTG-CTO7-40-04\",\r\n"
		+ "                                            \"buildingFlag\": 0,\r\n"
		+ "                                            \"resourceSpecification\": {\r\n"
		+ "                                                \"model\": \"FDB2103T-8\",\r\n"
		+ "                                                \"manufacturer\": \"HUAWEI\"\r\n"
		+ "                                            },\r\n"
		+ "                                            \"resourceCharacterist\": {\r\n"
		+ "                                                \"siteCode\": \"130010006\",\r\n"
		+ "                                                \"cityCode\": 13001000,\r\n"
		+ "                                                \"coordinateX\": -76.5147653444791,\r\n"
		+ "                                                \"coordinateY\": 3.37225504891685,\r\n"
		+ "                                                \"addressGPS\": \"(13001000) CARTAGENA\",\r\n"
		+ "                                                \"subUnit\": []\r\n"
		+ "                                            },\r\n"
		+ "                                            \"terminalLogicalCable\": [],\r\n"
		+ "                                            \"vlan\": []\r\n"
		+ "                                        },\r\n"
		+ "                                        \"terminalLogicalCable\": {\r\n"
		+ "                                            \"regionCode\": 13001000,\r\n"
		+ "                                            \"siteCode\": \"130010006\",\r\n"
		+ "                                            \"code\": \"GT7-40-04\",\r\n"
		+ "                                            \"function\": 7,\r\n"
		+ "                                            \"logicalUnit\": 1,\r\n"
		+ "                                            \"availableLogicalUnit\": []\r\n"
		+ "                                        }\r\n"
		+ "                                    }\r\n"
		+ "                                ],\r\n"
		+ "                                \"relatedAditionalResources\": []\r\n"
		+ "                            }\r\n"
		+ "                        }\r\n"
		+ "                    ]\r\n"
		+ "                },\r\n"
		+ "                \"supplementaryInformation\": {\r\n"
		+ "                    \"resourceOrderInfo\": {\r\n"
		+ "                        \"resourceOrderType\": \"OS\",\r\n"
		+ "                        \"resourceOrderDate\": \"2022-03-15T05:00:00.000Z\"\r\n"
		+ "                    },\r\n"
		+ "                    \"subscriberAddress\": {\r\n"
		+ "                        \"streetType\": \"DG\",\r\n"
		+ "                        \"streetName\": \"38\",\r\n"
		+ "                        \"streetCode\": \"SERV15543\",\r\n"
		+ "                        \"streetNumber\": \"TV 54-210\",\r\n"
		+ "                        \"subUnit\": [],\r\n"
		+ "                        \"city\": \"CARTAGENA\",\r\n"
		+ "                        \"stateAcronym\": \"BOL\",\r\n"
		+ "                        \"country\": \"Colombia\",\r\n"
		+ "                        \"regionCode\": 13001000,\r\n"
		+ "                        \"coordinateX\": -75.4660626852322,\r\n"
		+ "                        \"coordinateY\": 10.3967229047298\r\n"
		+ "                    },\r\n"
		+ "                    \"fiberSite\": 1,\r\n"
		+ "                    \"clientLogicalPosition\": 2\r\n"
		+ "                }\r\n"
		+ "            }\r\n"
		+ "        ]\r\n"
		+ "    },\r\n"
		+ "    \"result\": {\r\n"
		+ "        \"resultCode\": 0,\r\n"
		+ "        \"resultDescription\": \"OK\"\r\n"
		+ "    }\r\n"
		+ "}\r\n"
		+ "";
    }
}
